name = "InsumoProduto"
uuid = "13042449-f102-4a2d-ba59-b932bf3a5dbd"
authors = ["alanleal-econ <prof@alanleal-econ.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
